# Generated by Django 4.2.5 on 2023-10-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyQuickNumbersModel',
            new_name='MonthlyQuickNumbers',
        ),
    ]
