# Generated by Django 4.2.5 on 2023-10-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_rename_monthlyquicknumbersmodel_monthlyquicknumbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyQuickNumbers',
            new_name='MonthlyQuickNumber',
        ),
    ]
