# Generated by Django 4.2.5 on 2023-10-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_rename_monthlyquicknumbers_monthlyquicknumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyquicknumber',
            options={'verbose_name': 'Monthly Quick Number', 'verbose_name_plural': 'Monthly Quick Numbers'},
        ),
    ]
