# Generated by Django 4.2.5 on 2023-10-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0006_monthlyquicknumber_url_param_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyquicknumber',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
