# Generated by Django 4.2.5 on 2023-10-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0007_alter_monthlyquicknumber_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyquicknumber',
            old_name='url_param_value',
            new_name='url_param',
        ),
    ]
