# Generated by Django 4.2.5 on 2023-10-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0008_rename_url_param_value_monthlyquicknumber_url_param'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyquicknumber',
            old_name='url_param',
            new_name='url_parameter',
        ),
    ]
